---
version: '3.8'

networks:
  formance:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    hostname: jaeger
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_HTTP_HOST_PORT: 0.0.0.0:4318
      BADGER_EPHEMERAL: false
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      formance:
        ipv4_address: 10.0.0.15

  postgres:
    image: "postgres:15-alpine"
    hostname: postgres
    container_name: postgres
    command:
      - -c
      - max_connections=200
    environment:
      POSTGRES_USER: "ledger"
      POSTGRES_PASSWORD: "ledger"
      POSTGRES_DB: "ledger"
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ledger" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      formance:
        ipv4_address: 10.0.0.16

  ledger:
    image: "us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/ledger:latest"
    hostname: ledger
    container_name: ledger
    environment:
      STORAGE_DRIVER: "postgres"
      POSTGRES_URI: "postgresql://ledger:ledger@10.0.0.16:5432/ledger?sslmode=disable"
      BIND: ":8080"
      OTEL_TRACES: true
      OTEL_TRACES_EXPORTER: otlp
      OTEL_TRACES_EXPORTER_OTLP_ENDPOINT: 10.0.0.15:4318
      OTEL_TRACES_EXPORTER_OTLP_MODE: http
      OTEL_TRACES_EXPORTER_OTLP_INSECURE: true
      OTEL_SERVICE_NAME: ledger
    networks:
      formance:
        ipv4_address: 10.0.0.17
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started

  gateway:
    image: "ghcr.io/formancehq/gateway:v2.0.0-rc.20"
    hostname: gateway
    container_name: gateway
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:8080"
    networks:
      formance:
        ipv4_address: 10.0.0.18
    depends_on:
      - ledger
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 2s
      retries: 5
      start_period: 1s

  workload:
    image: "us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/workload:latest"
    hostname: workload
    container_name: workload
    networks:
      formance:
        ipv4_address: 10.0.0.19
    depends_on:
      - gateway
