VERSION 0.8

compile:
    FROM --platform=linux/amd64 golang:1.22.2
    RUN git clone --branch feat/antithesis-sdk https://github.com/formancehq/stack.git /go/stack
    RUN go install github.com/antithesishq/antithesis-sdk-go/tools/antithesis-go-instrumentor@latest
    WORKDIR /go/stack/components/ledger
    RUN cp -r /go/stack/libs /libs
    RUN go mod download
    RUN mkdir -p /ledger_instrumented
    RUN /go/bin/antithesis-go-instrumentor . /ledger_instrumented
    WORKDIR /ledger_instrumented/customer
    RUN go mod download
    RUN go build -race -o ledger
    SAVE ARTIFACT /ledger_instrumented/customer/ledger
    SAVE ARTIFACT /ledger_instrumented/symbols

build:
    FROM ubuntu:latest
    COPY (+compile/ledger) /bin/ledger
    COPY (+compile/symbols) /symbols
    RUN chmod 777 /bin/ledger
    EXPOSE 8080
    ENTRYPOINT ["ledger"]
    CMD ["serve"]

    SAVE IMAGE --push us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/ledger