VERSION 0.8

compile:
    FROM --platform=linux/amd64 golang:1.22.2
    RUN curl -s https://api.github.com/repos/formancehq/stack/git/refs/heads/feat/antithesis-sdk > /version.json
    GIT CLONE --branch feat/antithesis-sdk https://github.com/formancehq/stack.git /go/stack
    RUN go install github.com/antithesishq/antithesis-sdk-go/tools/antithesis-go-instrumentor@latest
    WORKDIR /go/stack/components/ledger
    RUN cp -r /go/stack/libs /libs
    RUN go mod download
    RUN mkdir -p /ledger_instrumented
    RUN /go/bin/antithesis-go-instrumentor . /ledger_instrumented
    WORKDIR /ledger_instrumented/customer
    RUN go mod download
    RUN go build -race -o ledger
    SAVE ARTIFACT /ledger_instrumented/customer/ledger
    SAVE ARTIFACT /ledger_instrumented/symbols
    SAVE ARTIFACT /version.json

build:
    FROM --platform=linux/amd64 ubuntu:latest
    COPY (+compile/ledger) /bin/ledger
    COPY (+compile/symbols) /symbols
    COPY (+compile/version.json) /version.json
    RUN chmod 777 /bin/ledger
    RUN apt-get update -y && apt-get install -y postgresql-client curl
    COPY entrypoint.sh /bin/entrypoint.sh
    COPY export.sh /bin/export.sh
    RUN chmod 777 /bin/entrypoint.sh
    EXPOSE 8080
    ENTRYPOINT ["/bin/entrypoint.sh"]

    SAVE IMAGE --push --no-manifest-list \
        us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/ledger:latest