VERSION 0.8

compile:
    FROM golang:1.22.2-alpine3.19
    WORKDIR /src
    COPY go.* *.go .
    RUN go build -o main
    SAVE ARTIFACT /src/main

build:
    FROM scratch
    COPY (+compile/main) /bin/workload
    ENTRYPOINT ["/bin/workload"]

    SAVE IMAGE --push us-central1-docker.pkg.dev/molten-verve-216720/formance-repository/workload